image: gentoo/stage3-amd64:latest

stages:
  - test
  - install

before_script:
  - mkdir /var/db/repos/gentoo
  - emerge-webrsync

test:
  stage: test
  script:
    - emerge dev-util/shellcheck-bin
    - bash test.sh

install:
  stage: install
  script:
    - emerge app-portage/cpuid2cpuflags
    - emerge app-admin/stow
    - bash install
    - emerge bash
