image: gentoo/stage3-amd64:latest

stages:
  - test
  - install

before_script:
  - mkdir /var/db/repos/gentoo
  - emerge-webrsync

test:
  stage: test
  script:
    - emerge -q dev-util/shellcheck-bin
    - bash test.sh

install:
  stage: install
  script:
    - emerge -q app-portage/cpuid2cpuflags
    - emerge -q app-admin/stow
    - bash install
    - emerge -q bash
