#!/bin/sh


# This file is part of genlica.

# genlica is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# genlica is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with genlica.  If not, see <https://www.gnu.org/licenses/>.

# Copyright (c) 2019-2021, XGQT
# Licensed under the GNU GPL v3 License


echo_msg() {
    echo "$(tput bold)$*$(tput sgr0)"
}


cd "$(dirname "${0}")" || exit 1

[ ! -d "${EPREFIX}/etc/portage" ] && echo_msg "No portage tree found" && exit 1
[ ! -d ./portage ] && echo_msg "No genlica's portage directory found" && exit 1

echo_msg "Differences between genlica's portage tree and the local one:"

diff -rq "${EPREFIX}/etc/portage/" ./portage | sed 's/:/ -->/g'
