#!/bin/sh


# This file is part of genlica.

# genlica is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# genlica is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with genlica.  If not, see <https://www.gnu.org/licenses/>.

# Copyright (c) 2019-2021, XGQT
# Licensed under the GNU GPL v3 License


trap 'exit 128' INT
set -e
export PATH


if [ -z "${1}" ]
then
    echo "Your commit message is empty!"
    exit 1
fi


if command -v qlist >/dev/null
then
    pkgs="$(qlist -CIev 'sys-apps/portage') $(qlist -CIev 'sys-apps/pkgcore')"
fi

cd "$(portageq get_repo_path / gentoo)"

_head="$(git rev-parse HEAD)"
if [ -n "${_head}" ]
then
    head="Head commit of repository gentoo: ${_head}"
fi

if [ -f metadata/timestamp.chk ]
then
    timestamp="Timestamp of repository gentoo: $(cat metadata/timestamp.chk)"
fi

cd - >/dev/null


msg="${*}

${pkgs}
${head}
${timestamp}"


echo "Message:
'''
${msg}
'''"


git add --verbose .

git commit --signoff --verbose --message="${msg}"

git pull --verbose
git push --verbose
