#!/bin/sh


trap 'exit 128' INT
set -e
export PATH


if [ -z "${1}" ]
then
    echo "Your commit message is empty!"
    exit 1
fi


if command -v qlist >/dev/null
then
    pkgs="$(qlist -CIev portage) $(qlist -CIev repoman) $(qlist -CIev pkgcore)"
fi

cd "$(portageq get_repo_path / gentoo)"

_head="$(git rev-parse HEAD)"
if [ -n "${_head}" ]
then
    head="Head commit of repository gentoo: ${_head}"
fi

if [ -f metadata/timestamp.chk ]
then
    timestamp="Timestamp of repository gentoo: $(cat metadata/timestamp.chk)"
fi

cd - >/dev/null


msg="${*}

${pkgs}
${head}
${timestamp}"


echo "Message:
'''
${msg}
'''"


git add --verbose .

git commit --signoff --verbose --message="${msg}"

git pull --verbose
git push --verbose
