#!/bin/sh


# Create /var/notmp as alternative
# to merging on /var/tmp


main_dir="/var/notmp/portage"


main() {

	if grep portage /etc/passwd >/dev/null
	then
		if [ ! -d $main_dir ]
		then
			mkdir -p $main_dir
			chown portage:portage $main_dir
		else
			echo "$main_dir already exists"
		fi
	else
		echo "No portage user found"
		exit 1
	fi
}


if [ "$(whoami)" != root ]
then
	sudo "${0}"
else
	main
fi
