#!/bin/sh


# This file is part of genlica.

# genlica is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# genlica is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with genlica.  If not, see <https://www.gnu.org/licenses/>.

# Copyright (c) 2019-2021, XGQT
# Licensed under the GNU GPL v3 License

# Create /var/notmp as alternative
# to merging on /var/tmp


main_dir="/var/notmp/portage"


main() {
    if grep portage /etc/passwd >/dev/null
    then
        if [ ! -d "${main_dir}" ]
        then
            mkdir -p "${main_dir}"
            chown portage:portage "${main_dir}"
        else
            echo "${main_dir} already exists"
        fi
    else
        echo "No portage user found"
        exit 1
    fi
}


if [ "$(whoami)" != root ]
then
    sudo "${0}"
else
    main
fi
