#!/bin/sh


# This file is part of genlica.

# genlica is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# genlica is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with genlica.  If not, see <https://www.gnu.org/licenses/>.

# shellcheck disable=2046

# Deselect packages from a set


main() {
    if [ -z "${1}" ]
    then
        echo "No set file given"
        echo "As argument (one) give a path to a set file"
        echo "Example: ${0} /etc/portage/sets/cs-hw"
        return 1
    else
        emerge --deselect $(sed '/^#/d' "${1}")
    fi
}


if [ "$(whoami)" != root ]
then
	sudo "${0}" "${1}"
else
	main "${1}"
fi
