#!/bin/sh


# This file is part of genlica.

# genlica is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# genlica is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with genlica.  If not, see <https://www.gnu.org/licenses/>.

# Copyright (c) 2019-2021, XGQT
# Licensed under the GNU GPL v3 License


trap 'exit 128' INT
export PATH


main() {
    # Auto-select the stow implementation
    if command -v stow >/dev/null 2>&1
    then
        stow_impl=stow
    elif command -v xstow >/dev/null 2>&1
    then
        stow_impl=xstow
    elif command -v pystow >/dev/null 2>&1
    then
        stow_impl=pystow
    else
        echo "There is no stow on the sytem! Exiting"
        exit 1
    fi

    cd "$(dirname "${0}")" || exit 1

    ${stow_impl} -D -v portage -t "${EPREFIX}/etc/portage"
    echo "There may be some trash left over"
}


if [ "$(whoami)" != root ]
then
    sudo "${0}"
else
    main
fi
