#!/bin/sh


trap 'exit 128' INT
export PATH


main() {
    # Auto-select the stow implementation
    if command -v stow >/dev/null 2>&1
    then
        stow_impl=stow
    elif command -v xstow >/dev/null 2>&1
    then
        stow_impl=xstow
    elif command -v pystow >/dev/null 2>&1
    then
        stow_impl=pystow
    else
        err_msg "There is no stow on the sytem! Exiting"
    fi

    cd "$(dirname "${0}")" || exit 1

    ${stow_impl} -D -v portage -t "${EPREFIX}/etc/portage"
    echo "There may be some trash left over"
}


if [ "$(whoami)" != root ]
then
    sudo "${0}"
else
    main
fi
