#!/bin/sh


# Update genlica


set -e
export PATH


main() {
    cd "$(dirname "${0}")" || exit 1

    # First reset any changes
    git reset --hard

    # Then safely remove links
    stow -D -v portage -t "${EPREFIX}/etc/portage"

    # Pull
    git pull

    # After taht link again
    stow -v portage -t "${EPREFIX}/etc/portage"
}


if [ "$(whoami)" != root ] && [ -z "${EPREFIX}" ]
then
    sudo "${0}"
else
    main
fi
