#!/usr/bin/env bash


# This file is part of genlica.

# genlica is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# genlica is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with genlica.  If not, see <https://www.gnu.org/licenses/>.


trap 'exit 128' INT
export PATH


main() {
    bash "${EPREFIX}/opt/genlica/update" -r
    if command -v emerge >/dev/null 2>&1
    then
        export ACCEPT_KEYWORDS="**"
        export ACCEPT_LICENSE="*"
        export FEATURES="-getbinpkg"
        emerge -v -1 --autounmask --jobs=1 \
               --usepkg-exclude \* --quiet-build=n genlica
    fi
    bash "${EPREFIX}/opt/genlica/update" -i
}


if [ -n "${1}" ]
then
    case "${1}" in
        -v | --version )
            cat << EOF
Genlica - Gentoo replica

Copyright (c) 2020, XGQT
Licensed under the GNU GPL v3 License

EOF
            distfile_dir="${EPREFIX}/var/cache/distfiles/git3-src/xgqt_genlica.git"
            if [ -d "${distfile_dir}" ]
            then
                cd "${distfile_dir}" || exit 1
                echo "Last changes:"
                GIT_PAGER='cat' git show
            fi
            ;;
        * )
            cat << EOF
Usage: update-genlica [OPTION]
update-genlica - script to update genlica

Options:
    -v  --version   show genlica version (commit)
    -h  --help      show this help information

Copyright (c) 2020, XGQT
Licensed under the ISC License
EOF
            ;;
    esac
else
    if [ "$(whoami)" != root ] && [ -z "${EPREFIX}" ]
    then
        sudo "${0}"
    else
        main
    fi
fi
