#!/usr/bin/env bash


# This file is part of genlica.

# genlica is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# genlica is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with genlica.  If not, see <https://www.gnu.org/licenses/>.

# Copyright (c) 2019-2021, XGQT
# Licensed under the GNU GPL v3 License

# Genlica Portage bashrc


# CCache

if [[ "${FEATURES}" == *ccache* && "${EBUILD_PHASE_FUNC}" == src_* ]]
then
    if [[ "${CCACHE_DIR}" == "${EPREFIX}"/var/cache/ccache ]]
    then
        # Set the ccache dir to whatever CCACHE_DIR is + category + name of the package
        export CCACHE_DIR="${EPREFIX}"/var/cache/ccache/${CATEGORY}/${PN}
        mkdir -p "${CCACHE_DIR}" || die "Failed to create ccache directory"
        # Copy ccache.conf if it is found in "old" CCACHE_DIR
        if [ -f "${EPREFIX}"/var/cache/ccache/ccache.conf ]
        then
            cp "${EPREFIX}"/var/cache/ccache/ccache.conf /var/cache/ccache/"${CATEGORY}"/"${PN}"/ccache.conf || die "Failed to copy ccache config"
        fi
    fi
fi


# Verbose ebuild phase

if [ -n "${EBUILD_PHASE}" ] && [ ! "${EBUILD_PHASE}" = "depend" ]
then
    echo "[ $(date +%H:%M:%S) ] ${EBUILD_PHASE^^} for version ${PV} of ${PN} from ${CATEGORY}"
fi
